spring:
  application:
    name: itmo-trip
  datasource:
    url: jdbc:postgresql://localhost/trip
    username: trip
    password: trip
  liquibase:
    url: ${spring.datasource.url}
    user: trip
    password: trip
    change-log: classpath:/db/master-changelog.yaml
  security:
    oauth2:
      client:
        registration:
          itmo-id:
            provider: itmo-id
            client-id: student-personal-cabinet
            redirect-uri: https://my.itmo.ru/login/callback
            authorization-grant-type: authorization_code
            client-authentication-method: "none"
        provider:
          itmo-id:
#            jwk-set-uri: https://id.itmo.ru/auth/realms/itmo/protocol/openid-connect/certs
            issuer-uri: https://id.itmo.ru/auth/realms/itmo
#            authorization-uri: https://id.itmo.ru/auth/realms/itmo/login-actions/authenticate
#            authorization-uri: https://id.itmo.ru/auth/realms/itmo/protocol/openid-connect/auth
#            token-uri: https://id.itmo.ru/auth/realms/itmo/protocol/openid-connect/token
#            user-info-uri: https://id.itmo.ru/auth/realms/itmo/protocol/openid-connect/userinfo


openapi:
  itmoTrip:
    base-path: /api/v1

logging:
  level:
    org.springframework.security: DEBUG
