version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: itmo-trip-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    # image: ghcr.io/itmo-trip/itmo.trip:master
    build: ../
    container_name: itmo-trip-backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "8080:8080"
      - "8081:8081"
    healthcheck:
      test: [
        "CMD-SHELL",
        "wget -T5 -qO- http://localhost:8080/itmo-trip/readyz | grep UP || exit 1"
      ]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  frontend:
    # image: ghcr.io/itmo-trip/itmo.trip-frontend:master
    build:
      context: .././frontend
      dockerfile: Dockerfile
#      platforms:
#        - "linux/amd64"
      args:
        - VITE_API_BASE=http://trips.itmo.tw1.su:8080/itmo-trip
        - VITE_API_TARGET=http://trips.itmo.tw1.su:8080
    container_name: itmo-trip-frontend
    environment:
      VITE_API_BASE: ${VITE_API_BASE}
      VITE_API_TARGET: ${VITE_API_TARGET}
    ports:
      - "5177:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512m'

volumes:
  postgres_data:
    name: "itmo-trip-postgres-data"
